### ISSUE TITLE
Accessing scalars from Python code

### ISSUE THREAD

**Issue by devos50** [ofek/coincurve#101]
I'm currently trying to write a few Python bindings around the [FROST algorithm](https://github.com/ElementsProject/secp256k1-zkp/pull/138). To get this up and running, I need to call the `secp256k1_scalar_chacha20` function, which signature seems to be defined [here](https://github.com/ElementsProject/secp256k1-zkp/blob/6db00f5b2e0986add852fa808ab485a25a9278f7/src/scalar.h#L109). The problem, however, is that I'm not entirely sure how to write the appropriate CFFI bindings to this function, given that the `scalar.h` file is in the `src` directory. The existing CFFI bindings are all related to header files in the `include` directory.

I tried to add the following line to the `_cffi_build/build.py` file:

```
Source('scalar.h', '#include <scalar.h>'),
```

I also created a `scalar.h` file in the `_cffi_build` directory with the following contents:

```
typedef struct {
    uint64_t d[4];
} secp256k1_scalar;

static void secp256k1_scalar_chacha20(
    secp256k1_scalar *r1,
    secp256k1_scalar *r2,
    const unsigned char *seed,
    uint64_t idx
);
```

When running `python3 setup.py build`, I'm getting the following error:

```
build/temp.macosx-11-x86_64-3.9/_libsecp256k1.c:570:10: fatal error: 'scalar.h' file not found
```

Anyone knows what I'm doing wrong here? Any help would be highly appreciated!

**Comment by MementoRC** [comment]
`coincurve` provides bindings for `libsecp256k1`, not `libsecp256k1-zkp`. The feature you are trying to access are not implemented in `libsecp256k1`.
@ofek given how old this is, I surmise the issue can be closed

**Comment by ofek** [comment]
Feel free to close this yourself at your leisure!

**Comment by MementoRC** [comment]
@devos50 Please re-open if you feel my assessment was incorrect or this was closed inappropriately. Thank you
