### ISSUE TITLE
No Python 3.10 wheels

### ISSUE THREAD

**Issue by sometato** [ofek/coincurve#106]
Hi Ofek!

It looks like there's no Python 3.10 wheels. In Docker with the python:3.9-slim image, I can `pip install coincurve` just fine. However, with `python:3.10-slim` it tries to compile and fails. `python:3.10` works fine as it has a C compiler.

Would it be possible to release Python 3.10 wheels for coincurve?

Thank you!

**Comment by ofek** [comment]
Sure, I'll do it this weekend!

**Comment by ofek** [comment]
https://pypi.org/project/coincurve/16.0.0/

**Comment by sometato** [comment]
Awesome! Thank you so much!
