### ISSUE TITLE
15.0.1 wheel file for MacOS ARM64

### ISSUE THREAD

**Issue by gurukamath** [ofek/coincurve#111]
Would it be possible to make a wheel available file for ARM64 for the version 15.0.1?
I am working on a project where this version is being used and the code does not seem to be compatible with v17.0.0 or 16.0.0

**Comment by ofek** [comment]
Describe incompatibility?

**Comment by gurukamath** [comment]
I get the following error. 
I have 

Python 3.8.9
coincurve 16.0.0

`
.tox/py3/lib/python3.8/site-packages/ethereum/crypto/elliptic_curve.py:8: in <module>
    import coincurve
.tox/py3/lib/python3.8/site-packages/coincurve/__init__.py:1: in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
.tox/py3/lib/python3.8/site-packages/coincurve/context.py:4: in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
.tox/py3/lib/python3.8/site-packages/coincurve/flags.py:1: in <module>
    from ._libsecp256k1 import lib
E   ImportError: dlopen(.tox/py3/lib/python3.8/site-packages/coincurve/_libsecp256k1.cpython-38-darwin.so, 0x0002): symbol not found in flat namespace '_secp256k1_nonce_function_default'
`

**Comment by ofek** [comment]
v17.0.0 too?

**Comment by gurukamath** [comment]
@ofek I see now that with v17.0.0, it works fine. Thank you.
