### ISSUE TITLE
Support for different encodings?

### ISSUE THREAD

**Issue by aneeshvaidya** [ofek/coincurve#12]
I don't know if this is in scope for this project, but would it make sense to support different encodings of keys as `pybitcointools` does?

**Comment by ofek** [comment]
Like this? https://github.com/vbuterin/pybitcointools/blob/aeb0a2bbb8bbfe421432d776c649650eaeb882a5/bitcoin/main.py#L177-L208

**Comment by aneeshvaidya** [comment]
Yes, but written in an easier to read and maintainable way

**Comment by ofek** [comment]
I'd prefer to just keep standard formats (hex, der, wif, etc.). Thanks for the suggestion though!

**Comment by roks0n** [comment]
@ofek which method represents the wif format in the [PrivateKey class](https://github.com/ofek/coincurve/blob/master/coincurve/keys.py#L22)?
