### ISSUE TITLE
one of coincurve users, ZeroNet, is dead and now is developed in multiple forks

### ISSUE THREAD

**Issue by caryoscelus** [ofek/coincurve#120]
please update the readme so as not to point to dead (and vulnerable) project site. upon ZeroNet death, a few forks have emerged, with two of them surviving to this day. as one of the forks maintainers, i don't want to influence your decision on which or whether even both forks to link, so i'll just drop links here for your consideration:

- https://github.com/zeronet-conservancy/zeronet-conservancy
- https://github.com/ZeroNetX/ZeroNet

**Comment by ofek** [comment]
thanks!
