### ISSUE TITLE
Signatures are not compatible with other libraries

### ISSUE THREAD

**Issue by keyvank** [ofek/coincurve#13]
Thank you for this great project!

The verify function sometimes returns False when I pass signatures of other libraries such as [python-ecdsa](https://github.com/warner/python-ecdsa) or [elliptic](https://github.com/indutny/elliptic) in JavaScript.
Another thing is that the sign function doesn't return signatures with more than 71 bytes. (As specified in your documentations and [Bitcoin Wiki](https://en.bitcoin.it/wiki/Elliptic_Curve_Digital_Signature_Algorithm) it is possible to have signatures with 72 bytes in size)

**Comment by ofek** [comment]
Thanks, I'm glad you like it!

1. probably they are using the insecure form https://github.com/bitcoin-core/secp256k1/blob/c95f6f1360a87bba61622cbaa0eb714c241a5d90/include/secp256k1.h#L426-L467
2. Bitcoin adds an extra byte at the end https://github.com/ofek/bit/blob/89dcd0a8d05b785691b34a9b28dee157ee419bea/bit/transaction.py#L221
