### ISSUE TITLE
missing dependencies when installing xxx.whl

### ISSUE THREAD

**Issue by MementoRC** [ofek/coincurve#143]
![image](https://github.com/ofek/coincurve/assets/93164135/0aced6c2-497c-4146-b23e-9ee0bd40c2b8)

**Comment by MementoRC** [comment]
This PR should resolve it https://github.com/ofek/coincurve/pull/142

**Comment by carterbox** [comment]
Is this error only on Windows?

**Comment by MementoRC** [comment]
> Is this error only on Windows?

Not sure, I did not try to reproduce it. It seemed to be related to a non-installed package with pyproject.toml that does not get the dependencies defined in pyproject installed - I did not understand it, nor replicate it locally
