### ISSUE TITLE
Can't install: cffi issue

### ISSUE THREAD

**Issue by wschwab** [ofek/coincurve#16]
**Error Message:** 
`pkg_resources.DistributionNotFound: The 'cffi>=1.3.0' distribution was not found and is required by the application`
**Problem:**
I have `cffi 1.10.0-1`
**Suggestion:**
line 253 in setup.py requires `'cffi>=1.3.0'`. Maybe it thinks 1 < 3 instead of seeing that it's 10 (Or that 1.3>1.10, which it really sort of is.) I wouldn't be sure how to write it to make sure that it's over 1.3, but still includes 1.10 and up.

**Comment by ofek** [comment]
Can you please paste the whole output?

**Comment by wschwab** [comment]
I managed to bypass the problem at some point, though I can't remember how right now. It may have been by deprecating `cffi` to 9.something, and then updating it.

**Comment by ofek** [comment]
Thanks, please let me know if you remember!

**Comment by ofek** [comment]
Thank you!
