### ISSUE TITLE
build wheels for Python 3.7

### ISSUE THREAD

**Issue by combstraight** [ofek/coincurve#19]
Hello,

When I use the command:  

python3 -m pip install coincurve,

I get the error:

Command "/Library/Frameworks/Python.framework/Versions/3.7/bin/python3 -u -c "import setuptools, tokenize;__file__='/private/var/folders/jt/_qtff9ts79gg38pn1qf7cjfh0000gn/T/pip-install-0bxfz20t/coincurve/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/jt/_qtff9ts79gg38pn1qf7cjfh0000gn/T/pip-record-ylcgs23y/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/jt/_qtff9ts79gg38pn1qf7cjfh0000gn/T/pip-install-0bxfz20t/coincurve/

It installs fine onto python 2.x but I need it to install to my python 3.x.  Please advice.  Thank you.

**Comment by ofek** [comment]
@combstraight Can you please try now?

**Comment by combstraight** [comment]
It's installed successfully.  However, when I try to import it, I get the following ImportError:

Traceback (most recent call last):
  File "/Users/yoonsuk/Desktop/python-idex-master/Idex.py", line 1, in <module>
    import coincurve
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/coincurve/__init__.py", line 1, in <module>
    from coincurve.context import GLOBAL_CONTEXT, Context
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/coincurve/context.py", line 4, in <module>
    from coincurve.flags import CONTEXT_ALL, CONTEXT_FLAGS
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/coincurve/flags.py", line 1, in <module>
    from ._libsecp256k1 import lib
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/coincurve/_libsecp256k1.cpython-37m-darwin.so, 2): Library not loaded: /usr/local/opt/gmp/lib/libgmp.10.dylib
  Referenced from: /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/coincurve/_libsecp256k1.cpython-37m-darwin.so
  Reason: image not found

**Comment by ofek** [comment]
@ulope Do you know why that might be happening?

**Comment by combstraight** [comment]
Hello,

I have ran coincurve successfully on my other computer that is running Python 3.6.5.

Perhaps Python 3.7 is the issue?
