### ISSUE TITLE
Converting hex keys 

### ISSUE THREAD

**Issue by GraphicalDot** [ofek/coincurve#27]
alice_priv = '63f896667523449ebfa5b302aac627eb0289a80b650acb290d70dfbe12ca80c8'
alice_pub = '0375186a31459f98ede30a4afa533e293c0afb38fcbb535d5daff2a74408c7e442'

bob_priv = 'a8c0ed9925ce6dca5453e2f58591bf581df81ca2598e1a0b456629b9d68546c1'
bob_pub = '020c6c19e9154b3a419437afc33ee06859db06c960e8ac8b2b8db33af2c54ad6f6'

alice_coin_priv =  coincurve.PrivateKey.from_hex(alice_priv)

Now,  i want to create diffi hellman ECC key from alice_priv and bob_pub, is this possible here?

**Comment by ofek** [comment]
- https://github.com/ofek/coincurve/tree/159954944d49b72601f4cd566a5ba19d647af8d5#coincurveprivatekey
- https://github.com/ofek/coincurve/blob/159954944d49b72601f4cd566a5ba19d647af8d5/tests/test_keys.py#L86-L90
