### ISSUE TITLE
FreeBSD Support?

### ISSUE THREAD

**Issue by teran-mckinney** [ofek/coincurve#3]
Hi ofek,

I am not too sure of why this is but pip won't even attempt to fetch coincurve for me.

```
# pip3 --version
pip 9.0.1 from /usr/local/lib/python3.5/site-packages (python 3.5)
# pip3 install coincurve
Collecting coincurve
  Could not find a version that satisfies the requirement coincurve (from versions: )
No matching distribution found for coincurve
```

Anything else with pip has been fine for me. I'm not too sure if you have an OS restriction set in place that it's seeing.

Where should I go to look into this?

Thank you,
Teran

**Comment by ofek** [comment]
Can you please try again? I've updated https://github.com/ofek/coincurve#installation

**Comment by teran-mckinney** [comment]
Thank you!

A bit closer, but not quite:

```
    config.status: executing depfiles commands
    config.status: executing libtool commands
    make: don't know how to make gen_context.o. Stop

    make: stopped in /tmp/pip-build-zesl1go_/coincurve/build/temp.freebsd-11.0-RELEASE-p9-amd64-3.5
```

I think I have the necessary packages. I wonder if it's invoking make or gmake, probably needs to use gmake.

**Comment by teran-mckinney** [comment]
Ok, if I clone https://github.com/bitcoin-core/secp256k1 `make` fails as such and `gmake` works. Is this something that needs to be fixed/worked around in secp256k1 or in coincurve?

**Comment by ofek** [comment]
Can you please tell me the exact commands you used to successfully build libsecp256k1?

**Comment by teran-mckinney** [comment]
Sure,

```
./autogen.sh
./configure
gmake # Instead of make
```

**Comment by ofek** [comment]
ok ty now what is the output of `python -c "import platform;print(platform.system())"`?

**Comment by teran-mckinney** [comment]
```
# python -c "import platform;print(platform.system())"
FreeBSD
```

**Comment by ofek** [comment]
Please try now.

**Comment by teran-mckinney** [comment]
Great! Thank you!

It works fine. I appreciate it.

**Comment by ofek** [comment]
No problem, enjoy!
