### ISSUE TITLE
specification for ECDH function on https://pypi.org/project/coincurve/

### ISSUE THREAD

**Issue by olehnikolaiev** [ofek/coincurve#50]
I've just read the specification on your website https://pypi.org/project/coincurve/ and mentioned that the result of this function is `sha256(x)`, where `x` is the first coordinate of elliptic curve's point which corresponds to `my_private_key * other's_party_public_key`. After that I went through the source code of https://github.com/bitcoin-core/secp256k1 which is used in your implementation. But they use completely different algorithm - in particular they do `sha256(x,y)` in some way. Can you please fix me if I wrong anywhere?

**Comment by ofek** [comment]
Thanks! Resolved via #49
