### ISSUE TITLE
The setup_support.py function _find_lib can return false positives

### ISSUE THREAD

**Issue by borderm** [ofek/coincurve#57]
As the title states, setup_support.py has a function _find_lib which can return false positives, this results in build errors.

I run Arch Linux, a package called [libsecp256k1](https://www.archlinux.org/packages/community/x86_64/libsecp256k1/) exists, however it does not include the ecdh features as they are still experimental. However, the setup.py script will still use the system library to build this because it only checks if secp256k1 is installed, not if it has ecdh enabled.

This will result in a build error like such

```
$ python setup.py build
Warning: 'keywords' should be a list, got type 'tuple'
running build
running build_py
running build_ext
generating cffi module 'build/temp.linux-x86_64-3.8/_libsecp256k1.c'
already up-to-date
building '_libsecp256k1' extension
gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -march=x86-64 -mtune=generic -O3 -pipe -fno-plt -fPIC -I/usr/include/python3.8 -c build/temp.linux-x86_64-3.8/_libsecp256k1.c -o build/temp.linux-x86_64-3.8/build/temp.linux-x86_64-3.8/_libsecp256k1.o
build/temp.linux-x86_64-3.8/_libsecp256k1.c:493:10: fatal error: secp256k1_ecdh.h: No such file or directory
  493 | #include <secp256k1_ecdh.h>
      |          ^~~~~~~~~~~~~~~~~~
compilation terminated.
error: command 'gcc' failed with exit status 1
```

**Comment by ofek** [comment]
Nice find! Do you have a fix in mind?

**Comment by borderm** [comment]
An easy solution that will work, if inefficiently, is to just assume no system library exists. I also imagine there's a clever way of checking via cffi, but I'm not familiar with cffi. My solution of choice would be to check if `/usr/include/secp256k1_ecdh.h` exists after confirming the library exists.

I have a patch that should work, except I'm getting two odd errors that I'm fairly certain are unrelated in fresh copies of the repo. I'll probably have something tomorrow.

**Comment by ofek** [comment]
#58
