### ISSUE TITLE
urandom is not best for cryptography

### ISSUE THREAD

**Issue by mrx23dot** [ofek/coincurve#59]
utils.py / urandom is less secure than import secret

"In particularly, secrets should be used in preference to the default
pseudo-random number generator in the random module, which is designed
for modelling and simulation, not security or cryptography."
https://docs.python.org/3/library/secrets.html
 
usage:
secrets.token_bytes(16) -> b'\xebr\x17D*t\xae\xd4\xe3S\xb6\xe2\xebP1\x8b'
secrets.token_hex(16)  ->'f9bf78b9a18ce6d46a0cd2b0b86df9da'
instead of for i in range(16): secrets.token_bytes(1)
 
I wouldn't compromise security for speed. Or you could have a parameter unsecure=False).
People already building on top of this lib.

**Comment by ofek** [comment]
Hello! I think you are confusing urandom with the random module.

https://github.com/python/cpython/blob/a63c61168588937c482435d0432c753de4844c46/Lib/secrets.py#L47
