### ISSUE TITLE
ModuleNotFoundError: No module named 'coincurve._libsecp256k1'

### ISSUE THREAD

**Issue by SuperCipher** [ofek/coincurve#72]
After pip install coincurve and I try to import coincurve
<img width="580" alt="Screen Shot 2020-11-23 at 21 57 26" src="https://user-images.githubusercontent.com/6429197/100049790-bb506d80-2e4a-11eb-9097-e83d7f917a2e.png">
environment detail 
https://github.com/SuperCipher/coincurve/blob/d0bc945a1ee6e937944257489c33e0bfac83be85/.gitpod.Dockerfile#L1

**Comment by ofek** [comment]
Can you show the installation step?

**Comment by SuperCipher** [comment]
@ofek 
I setup docker with this config
https://github.com/SuperCipher/coincurve/blob/SuperCipher/gitpod-setup/.gitpod.Dockerfile
and run `pip install .` inside coincurve directory.
then I try import coincurve in python.

**Comment by ofek** [comment]
Can you show the Docker run command?

**Comment by SuperCipher** [comment]
`docker run -it cdcb8220e8aa /bin/bash`

**Comment by ofek** [comment]
Cannot reproduce anymore
