### ISSUE TITLE
f strings not supported on python 2. Cant install with pip2

### ISSUE THREAD

**Issue by devturi** [ofek/coincurve#95]
I have tried to install it but I am getting the following syntax error.

Collecting coincurve
  Using cached https://files.pythonhosted.org/packages/65/31/9f13921cc7ca27059af4def1a9d1277a6a252dea967b62f9ea05cc2a4115/coincurve-15.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "c:\users\abidja~1\appdata\local\temp\pip-build-kfxj2q\coincurve\setup.py", line 38
        LIB_TARBALL_URL = f'https://github.com/bitcoin-core/secp256k1/archive/{UPSTREAM_REF}.tar.gz'
                                                                                                   ^
    SyntaxError: invalid syntax

**Comment by ofek** [comment]
https://ofek.dev/coincurve/history/#1500
