### ISSUE TITLE
instance method `pubkey.combine` ignores self, is same as class method `PublicKey.combine_keys`

### ISSUE THREAD

**Issue by eric-downes** [ofek/coincurve#96]
The following assert fails for elliptic curve point addition:
```
from coincurve.keys import PublicKey, PrivateKey
pk_a = PrivateKey.from_int(22).public_key
pk_b = PrivateKey.from_int(99).public_key
pk_ab = PublicKey.combine_keys([pk_a, pk_b])
shouldbe_pk_ab = pk_a.combine([pk_b])
assert shouldbe_pk_ab == pk_ab
```

In fact, in the above `shouldbe_pk_ab == pk_b` holds.  This can be seen by examining `pk_b.point()` etc.  This is because the [relevant loop](https://github.com/ofek/coincurve/blob/0bb42ce2d97e7ded8181b10e6a96122865c9854f/coincurve/keys.py#L473) in `combine` is the same as in the class method [combine_keys](https://github.com/ofek/coincurve/blob/0bb42ce2d97e7ded8181b10e6a96122865c9854f/coincurve/keys.py#L363)

In both cases this is the list passed to `lib.secp256k1_ec_pubkey_combine`:
``` 
[pk.public_key for pk in public_keys]
```
notably, in `combine()` `self` is not in that list!

Perhaps, best practice is to avoid code duplication.  Something like:
```
def combine(self, public_keys: list, update: bool = False) -> PublicKey:
        new_key = PublicKey.combine_keys(public_keys + [self], context = self.context)
        if update:
                self.public_key = new_key.public_key
                return self
        return new_key
```

Great module, thanks for your hard work!

**Comment by ofek** [comment]
Thank you!!! Fixed: https://pypi.org/project/coincurve/15.0.1/
